// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egylejivtcnromfhkezq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVneWxlaml2dGNucm9tZmhrZXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTgyMzEsImV4cCI6MjA1OTI5NDIzMX0.w25rcqh6UM49pxygkTgCU5aZgwjd2L4_3olthr1omEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);